// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
    db: {
      schema: "public",
    },
    global: {
      headers: {
        "x-my-custom-header": "barberflow-pro",
      },
    },
  },
);

// Connection status monitoring
export const monitorConnection = () => {
  const channel = supabase.channel("connection-monitor");

  channel.subscribe((status) => {
    if (status === "SUBSCRIBED") {
      console.log("✅ Realtime connection established");
    } else if (status === "CHANNEL_ERROR") {
      console.error("❌ Realtime connection failed");
    } else if (status === "TIMED_OUT") {
      console.warn("⏱️ Realtime connection timed out");
    } else if (status === "CLOSED") {
      console.warn("🔌 Realtime connection closed");
    }
  });

  return channel;
};

// Health check function
export const checkSupabaseHealth = async (): Promise<boolean> => {
  try {
    const { error } = await supabase.from("clients").select("id").limit(1);
    return !error;
  } catch {
    return false;
  }
};
